from RunMe import Product, VideoGame, Book, Bundle

def main():
    sunglasses = Product("Vans Hip Cat Sunglasses", 14)
    print(Product.category)
    print(Product.next_serial_number)
    print(sunglasses.id)
    print(sunglasses.description)
    print(sunglasses.list_price)
    print(sunglasses.stock)
    print(sunglasses.reviews)
    print(sunglasses.sales)

    headphones = Product("Apple Airpods", 159)
    sunglasses.restock(20)
    headphones.restock(5)
    print(sunglasses)
    print('\n')
    print(headphones)
    print('\n')
    sunglasses.sell(3, 14)
    sunglasses.sell(1, 10)
    print(sunglasses.sales)
    headphones.sell(8, 140)  # There are only 5 available
    print(headphones.sales)
    print(sunglasses)
    print('\n')
    print(headphones)
    print('\n')
    sunglasses.restock(10)
    print(sunglasses)
    headphones.restock(20)
    print(headphones)
    print('\n')
    sunglasses.review(5, "Great sunglasses! Love them.")
    sunglasses.review(3, "Glasses look good but they scratch easily")
    headphones.review(4, "Good but expensive")
    print(sunglasses.reviews)
    print('\n')
    print(headphones.reviews)

    print(Product.category)

    print(Product.next_serial_number)

    print('\n')
    print('-------------Part II--------------')
    print(sunglasses.lowest_price)
    print(sunglasses.average_rating)
    backpack = Product("Nike Explore", 60)
    print(backpack.average_rating)
    print(backpack.lowest_price)
    print('\n')
    print('-------------Part III--------------')
    mario = VideoGame('Mario Tennis Aces', 50)
    mario.restock(10)
    mario.sell(3, 40)
    mario.sell(4, 35)
    print(mario)
    print(mario.lowest_price)

    mario.review(5, "Fun Game!")
    mario.review(3, "Too easy")
    mario.review(1, "Boring")

    print(mario.average_rating)
    print('\n')
    lego = VideoGame('LEGO The Incredibles', 30)
    print(lego)
    print('\n')
    lego.restock(5)
    lego.sell(10, 20)
    print(lego)
    print('\n')
    print(lego.lowest_price)
    print(VideoGame.category)
    print(VideoGame.next_serial_number)
    print(lego.id)

    print('\n-------------Part IV--------------')
    book1 = Book("The Quick Python Book", "Naomi Ceder", 472, 39.99)
    print(book1.author)
    print(book1.pages)
    print('')
    book1.restock(10)
    book1.sell(3, 30)
    book1.sell(1, 32)
    book1.review(5, "Excellent how to guide")
    print(book1)
    print('')
    print(book1.average_rating)
    print(book1.lowest_price)
    print('')
    book2 = Book("Learning Python", "Mark Lutz", 1648, 74.99)
    book1.restock(20)
    book1.sell(2, 50)
    print(book2)
    print('')
    print(book1 > book2)
    print(book1 < book2)
    print('')
    print(Book.category)
    print(Book.next_serial_number)
    print('\n-------------Part V--------------')
    bundle1 = Bundle(sunglasses, backpack, mario)
    print(bundle1)
    print('')
    bundle1.restock(3)
    bundle1.sell(1, 90)
    print(bundle1)
    print('')
    bundle1.sell(2, 95)
    print(bundle1)
    print('')
    bundle1.restock(3)
    bundle1.sell(1, 90)
    print(bundle1)
    print('')
    bundle1.sell(3, 95)
    print(bundle1)
    print('')
    print(bundle1.lowest_price)
    print('')
    bundle2 = Bundle(book1, book2)
    bundle2.restock(2)
    print(bundle2)
    print('')
    print(Bundle.category)
    print('')
    print(Bundle.next_serial_number)
    print('')
    print(Bundle.bundle_discount)
    print('\n-------------Part VI--------------')
    back_to_school_bundle = backpack + book1
    print(back_to_school_bundle)
    print('')
    best_bundle = sunglasses + headphones + book1 + mario
    print(best_bundle)
    print('')
    print(Bundle.next_serial_number)
main()
